### ISSUE TITLE
DecryptorSuite

### ISSUE THREAD

**Issue by chidich** [WodsonKun/JustDanceTools#1]
Hello, I was trying to convert 2014 files using the DecryptorSuite but the tool doesn't output anything. I am attempting to convert a timeline.tpl.ckd file specifically.

**Comment by WodsonKun** [comment]
Hey there!

Well, the decryptors are missing some files at the moment, and honestly, I forgot to search for them
I'll rewrite the DecryptorSuite in a few hours, expect a new update in 5 / 6 hours

Thank you for your attention! 😉

**Comment by chidich** [comment]
Thanks for the quick reply, I look forward to using the tools :)

**Comment by WodsonKun** [comment]
Sorry, for the late update
I'm still working on the decryptor, so it's gonna take a few hours before I upload it again

**Comment by WodsonKun** [comment]
@chidich So, the DeserializerSuite is finally fixed at all
Give it a try

**Comment by chidich** [comment]
just used it with a 2014 timeline.. works great! thank you so much for this! really appreciate it :)

**Comment by WodsonKun** [comment]
@chidich I'm glad that you liked it!
Make sure to update it again, added a quick fix to the CoachId
