### ISSUE TITLE
MediaTool - PC Amb Issue

### ISSUE THREAD

**Issue by stevenboeren** [WodsonKun/JustDanceTools#4]
So after install of ffmpeg, mkclean and VGAudioCli
I still couldn't use the pc amb command.
How do I fix this or is this a bug??

![image](https://user-images.githubusercontent.com/70892306/174499256-0c6889d5-e614-40d9-942e-609acc6f262d.png)

**Comment by WodsonKun** [comment]
The issue was already fixed on the lastest update
