### ISSUE TITLE
JSON2DTAPE problem

### ISSUE THREAD

**Issue by HerbataOwocowa** [WodsonKun/JustDanceTools#5]
I tried using the "JSON2DTAPE" tool and once it starts "converting" nothing happens but this error
![Screen](https://user-images.githubusercontent.com/112390759/187182885-48701dbb-a016-4f80-98da-66eb4125675c.png)

**Comment by WodsonKun** [comment]
Can you send a screenshot of how your JSON looks, please?
This looks more like a JSON issue, than a tool issue

**Comment by HerbataOwocowa** [comment]
![obraz](https://user-images.githubusercontent.com/112390759/189481899-afb97dcb-cc8f-41d4-b03a-67d52891985b.png)

**Comment by WodsonKun** [comment]
Yeah, it's a JSON issue
You have to remove the "Codename(" at the top of the JSON
And the ")" at the end

Save it and try again

**Comment by HerbataOwocowa** [comment]
It works! Thanks!!!
