### ISSUE TITLE
Next2UAF generates doesn't generate songcolor_1b

### ISSUE THREAD

**Issue by alexo310** [WodsonKun/JustDanceTools#7]
so i was modding thank u next, and i found out that the script doesn't generate the songcolor_1b value. instead it generates a songcolor_2b value.
![image](https://user-images.githubusercontent.com/94218972/230423878-3472845c-8cb4-4ece-be56-7cc98cc353d8.png)

**Comment by WodsonKun** [comment]
LMAO I FORGOT

**Comment by WodsonKun** [comment]
KKKKKKKKKKKKKKKK

**Comment by WodsonKun** [comment]
I'll fix it as soon as possible, don't worry
Thank u for pointing it out for me

I'll close the issue as soon as I fix it ❤️
