### ISSUE TITLE
American Boy Json has an error

### ISSUE THREAD

**Issue by alexo310** [WodsonKun/JustDanceTools#8]
self-explanatory
![image](https://github.com/WodsonKun/JustDanceTools/assets/94218972/8d5ddde5-ac00-4bca-8454-f9478a1e0ef9)

**Comment by WodsonKun** [comment]
The "issues" section is only related to problems/issues of the tools avaliable on this repository

Also, this JSON is probably from another of my repositories (jdcosmos-repo), and I don't give support to it.
As a matter of fact, that repository is only public for showcasing.
And before using anything of that, besides being Ubisoft's content and private property, please credit me, DieguinDG, RickL and Floup, as we spent a bunch of time creating and reuploading those JSONs/Medias.

Thanks for your attention!
